### ISSUE TITLE
sincere request

### ISSUE THREAD

**Issue by Tziyi7** [arjnklc/D2D-Caching-Simulation#1]
I saw your code and am very interested in this direction. There are some places I don't particularly understand, and I don't know if there are corresponding papers or documents. If so, I hope you can provide it. Anyway, I wish you a happy life.

**Comment by arjnklc** [comment]
Hello there,

I implemented 3 different cache algorithms here. One of them is LRU (Least Recently Used) which is one of the most popular cache algorithms. Second one is from a paper named Multi-level PLRU Cache Algorithm for Content Delivery Networks. You can find the corresponding paper [here](https://ieeexplore.ieee.org/document/8275780/). Last implementation is my heuristic approach using a score to decide which items cache should purge. Hope this helps
